source 'https://rubygems.org'

gem 'rack', '~> 1.6.0'
gem 'grape', '~> 0.12.0'
gem 'activerecord', '~> 4.2.0', require: 'active_record'
gem 'grape-activerecord', '~> 1.0.3'
gem 'mysql2', '~> 0.3.20'
gem 'rake'
gem 'twitter_oauth'
gem 'grape-route-helpers'
gem 'twitter'
